### ISSUE TITLE
Deployment on Netlify/Vercel

### ISSUE THREAD

**Issue by Siddhant-K-code** [Open-Sourced-Olaf/Code-Kindle#50]
**Is your feature request related to a problem? Please describe.**
Heroku Deployments takes more time to load for user, because of servers.

**Describe the solution you'd like**
Deployment on Vercel/Netlify/ etc. because they provide too quick response time.

**Comment by anjalisoni3655** [comment]
> **Is your feature request related to a problem? Please describe.**
> Heroku Deployments takes more time to load for user, because of servers.
> 
> **Describe the solution you'd like**
> Deployment on Vercel/Netlify/ etc. because they provide too quick response time.
> 
> 

Hey, yah I too have noticed this issue with heroku, but instead of netlify or heroku, can you deploy it to Dfinity as well.

**Comment by Siddhant-K-code** [comment]
yeah, I was just suggesting the alternative, you can use others too ( if they allowing fast response time ). Please finalize one, so we can start working towards it.

**Comment by anjalisoni3655** [comment]
> yeah, I was just suggesting the alternative, you can use others too ( if they allowing fast response time ). Please finalize one, so we can start working towards it. 

Yah, you can start with either vercal or Dfinity, please also update the readme for the steps to deploy locally
