### ISSUE TITLE
Create pseudocode for cpp

### ISSUE THREAD

**Issue by anjalisoni3655** [Open-Sourced-Olaf/Code-Kindle#8]
- Making a cpp pseudocode generator.

**Comment by Siddhant-K-code** [comment]
The deployed converter is not working, I tried to convert this :

```cpp
#include <iostream>
using namespace std;

int main(){
int a = 10,b = 5;
if(a>b){
cout<<"A is large";
  }
  else{
  cout<<"B is large";
  }
}
```

hits the `convert` button but nothing comes out in the output .. or i am doing something wrong with example fo source code

**Comment by anjalisoni3655** [comment]
> The deployed converter is not working, I tried to convert this :
> 
> ```cpp
> #include <iostream>
> using namespace std;
> 
> int main(){
> int a = 10,b = 5;
> if(a>b){
> cout<<"A is large";
>   }
>   else{
>   cout<<"B is large";
>   }
> }
> ```
> 
> hits the `convert` button but nothing comes out in the output .. or i am doing something wrong with example fo source code 

The server is not hosted right now. Were you testing locally? And yah there is some indentation/line issue sometimes with the cpp converters but it works.

**Comment by anjalisoni3655** [comment]
Declare Function main
Declare 6 Integer variable a = 10 b = 5 
Check if a>b
   If True then : 
Print  A
Print  is
Print  large
Print  B
Print  is
Print  large
> Here is the pseudocode generated by the converter

**Comment by Siddhant-K-code** [comment]
> The server is not hosted right now. Were you testing locally? And yah there is some indentation/line issue sometimes with the cpp converters but it works.

yeah, I was testing on Heroku deployment, will test it out local server now and will try to optimize converters.

**Comment by Siddhant-K-code** [comment]
> Declare 6 Integer variable a = 10 b = 5

shouldn't it be a 

*Declare 2 Integer  variable a = 10 b = 5*

**Comment by Siddhant-K-code** [comment]
Also, `endl` is not getting ignored!

**Comment by Siddhant-K-code** [comment]
> > Declare 6 Integer variable a = 10 b = 5
> 
> shouldn't it be a
> 
> Declare **2** Integer variable a = 10 b = 5

this can be fix using `temp.size() - var_name.size() + 1` at #L184 && #L185

before : `outFile << "Declare " << var_name.size() << " " << keyword[Data_type] << " variable ";`

after: `outFile << "Declare " << temp.size() - var_name.size() + 1 << " " << keyword[Data_type] << " variable ";`


but we have to create string temp = "" globally and implementing actions on that but then, this is causing error  like this: 


![image](https://user-images.githubusercontent.com/55068936/115100629-7349f880-9f5b-11eb-9fa5-cb7de3f8e2f6.png)


Lots of vars. are showing.

**Comment by Siddhant-K-code** [comment]
fixed the issue, creating PR

**Comment by anjalisoni3655** [comment]
> fixed the issue, creating PR

Great!! I will have a look.
